apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "facts"
  MYSQL_PASSWORD: "secret"
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_ALLOW_EMPTY_PASSWORD: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      storage: db
  template:
    metadata:
      labels:
        storage: db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mysql-config
          volumeMounts:
            # - name: node-storage
            #   mountPath: /var/lib/mysql
            - name: persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        # - name: node-storage
        #   hostPath:
        #     path: /data/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    storage: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
