apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec: 
  replicas: 3
  # here we define the pod template
  template:
    # kind: Pod
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: docker-api:latest

