services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - db/mysql.env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 10
  api:
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    environment:
      - PROFILE=dev
      - DB_URL=jdbc:mysql://db:3306/facts
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      db:
        condition: service_healthy
  web:
    build: ./web
    ports:
      - 4200:4200
    # container_name: web
    volumes:
      - ./web:/app
    depends_on:
      - api
  npm:
    image: node:21
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./web:/var/www/html

volumes:
  data:
