apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploymeny
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: webp:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: web-service
                port:
                  number: 4200
            path: /
            pathType: Prefix